name: nodejs
description: "Nodejs Stack"
displayedName:
icon:
versions:
- version: 1.0.1
  git:
    url:
    revision:
- version: 1.1.0
  default: true #should have one and only one default version
- version: 1.2.0
